# Generated by Django 3.0.7 on 2020-12-13 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190905_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_name',
            new_name='flight_name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='source',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='time',
        ),
        migrations.AddField(
            model_name='bus',
            name='depert_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 6, 5, 58, 666985)),
        ),
        migrations.AddField(
            model_name='bus',
            name='destination_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 6, 5, 58, 667063)),
        ),
        migrations.AddField(
            model_name='bus',
            name='fare',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='flight_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='fromm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='to',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
