# Generated by Django 3.0.7 on 2020-12-13 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201213_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='depert_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bus',
            name='destination_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
