# Generated by Django 3.0.7 on 2020-12-13 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201213_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='time1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bus',
            name='date1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bus',
            name='flight_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='time1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
