# Generated by Django 3.0.7 on 2020-12-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201213_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='flight_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
